backend:
  name: github
  repo: Alxandr/alxandr.me
  base_url: https://alxandr.me
  auth_endpoint: api/authorize

publish_mode: editorial_workflow
media_folder: public/content/img
public_folder: /content/img

collections:
  - name: blog # Used in routes, e.g., /admin/collections/blog
    label: Blog # Used in the UI
    label_singular: Post
    folder: posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', label_singular: 'tag' }
      - { label: 'Series', name: 'series', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
